#+property: header-args:emacs-lisp :tangle (concat (file-name-sans-extension (buffer-file-name)) ".el")
#+property: header-args :mkdirp yes :comments no
#+startup: indent

#+title: My Emacs Configuration File
#+author: Simen Omholt-Jensen

* Performance Optimization

Define a hook that reports how long and how many garbage collections the startup took. The hook runs the code at the very end, so messages doesn't get clobbered by other messages during startup.

#+begin_src emacs-lisp
  (add-hook 'emacs-startup-hook
            (lambda ()
              (message "Emacs ready in %s with %d garbage collections."
                       (format "%.2f seconds"
                               (float-time
                                (time-subtract after-init-time before-init-time)))
                       gcs-done)))
#+end_src

Wrap entire =init.el= file in a block that sets =file-name-handler-alist= to =nil=. This prevents any special-filename parsing of files loaded from the init file (e.g. remote files loaded through tramp, etc.). The =let= block gets closed at the end.

#+BEGIN_SRC emacs-lisp
  (let ((file-name-handler-alist nil))
#+END_SRC

Optionally, enable =debug-on-error=. For config debugging purposes.

#+BEGIN_SRC emacs-lisp
  ;; (setq debug-on-error t)
#+END_SRC

Prevent garbage collection during startup load time by setting =gc-cons-threshold= MAX. This is reset after load.

#+BEGIN_SRC emacs-lisp
  (setq gc-cons-threshold most-positive-fixnum)
#+END_SRC

* Package Management
** Bootstrap =use-package= as package manager.

Used to cleanly install and configure packages.

#+BEGIN_SRC emacs-lisp
  (customize-set-variable 'package-archives
			  '(("marmalade" . "https://marmalade-repo.org/packages/")
			    ("melpa" . "https://melpa.org/packages/")))
#+END_SRC

Package system is then initialized, the list of packages are refreshed, and =use-package= is installed if not already. Lastly, =use-package= is loaded.

#+BEGIN_SRC emacs-lisp
  (package-initialize)

  (when (not package-archive-contents)
    (package-refresh-contents))

  (when (not (package-installed-p 'use-package))
    (package-install 'use-package))

  (require 'use-package)
#+END_SRC

** Configure =use-package=

- The =use-package-always-ensure= variable indicates that =use-package= should always try to install missing packages. For some libraries this is not appropriate, and in those cases, =:ensure nil= is included as part of the =use-package= statement. This applies mainly to libraries which are installed as part of some other package (e.g. =org-mode= libraries).

#+BEGIN_SRC emacs-lisp
  (customize-set-variable 'use-package-always-ensure t)
#+END_SRC

- The =use-package-always-defer= set =:defer true= as the default for all package declarations. This makes Emacs startup much faster by preventing packages from being loaded when Emacs starts, and only doing so when they are needed. Some packages don't work well with this, so you'll see some declarations where =:defer nil= is explicitly set, to force the package to be loaded at startup. Further, =:defer n= is used to load the package, but only =n= seconds after startup.

#+BEGIN_SRC emacs-lisp
  (customize-set-variable 'use-package-always-defer t)
#+END_SRC

- The =use-package-verbose= variable enables verbose loading of packages, which is useful for debugging. Variable is set/unset according to need.

#+BEGIN_SRC emacs-lisp
     (customize-set-variable 'use-package-verbose nil)
#+END_SRC

** Configure =quelpa=

Install =quelpa= to install packages directly from github repositories. =quelpa-use-package= allows integration from within =use-package=.

#+BEGIN_SRC emacs-lisp
  (use-package quelpa
               :defer nil)

  (use-package quelpa-use-package
               :defer nil
               :after quelpa)
#+END_SRC

** Prefer newer =.el= files over older compiled =.elc= files

Also prefer =auto-compile= to autocompile files as needed.


#+BEGIN_SRC emacs-lisp
  (customize-set-variable 'load-prefer-newer t)
  (use-package auto-compile
    :defer nil
    :config (auto-compile-on-load-mode))
#+END_SRC

** Load other package folders

- =custom.el=

Load default configurations from the Emacs =custom.el= file. Configurations are flexible.

#+BEGIN_SRC emacs-lisp
  (setq custom-file "~/.emacs.d/custom.el")
  (load custom-file)
#+END_SRC

- =lisp=

Set the load path to directories which include other lisp code which sometimes are used.

#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path "~/.emacs.d/lisp")
#+END_SRC

* Settings

- Load the =cl= library to enable some additional macros (e.g. =lexical-let=).

#+BEGIN_SRC emacs-lisp
  (require 'cl)
#+END_SRC

- Start the Emacs server

#+BEGIN_SRC emacs-lisp
  (server-start)
#+END_SRC

- When =time-stamp= is run before every save, the string =Time-stamp: <>= in the first 8 lines of the file will be updated with the current timestamp.

#+BEGIN_SRC emacs-lisp
  (add-hook 'before-save-hook 'time-stamp)
#+END_SRC

- When at the beginning of a line, make =C-k= remove the whole line, instead of just emptying it.

#+BEGIN_SRC emacs-lisp
  (customize-set-variable 'kill-whole-line t)
#+END_SRC

- Paste text where the cursor is, not where the mouse is.

#+BEGIN_SRC emacs-lisp
(customize-set-variable 'mouse-yank-at-point t)
#+END_SRC

- Make completion case-insensitive

#+BEGIN_SRC emacs-lisp
  (setq completion-ignore-case t)
  (customize-set-variable 'read-file-name-completion-ignore-case t)
  (customize-set-variable 'read-buffer-completion-ignore-case t)
#+END_SRC

- Show line numbers with =display-line-numbers-mode=, which has no perceivable performance impact even on very large files.

#+BEGIN_SRC emacs-lisp
  (when (>= emacs-major-version 26)
    (use-package display-line-numbers
                 :defer nil
                 :ensure nil
                 :config
                 (global-display-line-numbers-mode)))
#+END_SRC

- Put all backup files in =~/.emacs.d/backups=

#+BEGIN_SRC emacs-lisp
  (customize-set-variable 'backup-directory-alist
                          `(("." . ,(concat user-emacs-directory "backups"))))
#+END_SRC

- Highlight matching parenthesis

#+BEGIN_SRC emacs-lisp
  (show-paren-mode)
#+END_SRC

- Don't use hard tabs. Insert spaces instead of <tab>

#+BEGIN_SRC emacs-lisp
  (customize-set-variable 'indent-tabs-mode nil)'
#+END_SRC

- Add "unfill" commands to parallel the "fill" ones, bind ~A-q~ to =unfill-paragraph= and rebind ~M-q~ to the =unfill-toggle= command, which fills/unfills paragraphs alternatively.

#+BEGIN_SRC emacs-lisp
  (use-package unfill
    :bind
    ("M-q" . unfill-toggle)
    ("A-q" . unfill-paragraph))
#+END_SRC

- Save the place of the cursor in each file, and restore it upon opening it again.

#+BEGIN_SRC emacs-lisp
  (use-package saveplace
    :defer nil
    :config
    (save-place-mode))
#+END_SRC

- Smooth scrolling (line by line) instead of jumping by half-screens.

#+BEGIN_SRC emacs-lisp
  (use-package smooth-scrolling
    :config
    (smooth-scrolling-mode 1))
#+END_SRC

- Delete trailing whitespace before saving a file.

#+BEGIN_SRC emacs-lisp
  (add-hook 'before-save-hook 'delete-trailing-whitespace)
#+END_SRC

- Suppress "ad-handle-definition: ... redefined" warnings during Emacs startup.

#+BEGIN_SRC emacs-lisp
  (customize-set-variable 'ad-redefinition-action 'accept)
#+END_SRC

- WinnerMode makes it possible to cycle and undo window configuration changes (i.e. arrangement of panels, etc.)

#+BEGIN_SRC emacs-lisp
  (when (fbound 'winner-mode) (winner-mode))
#+END_SRC

* System Specific Configuration

* Close =file-name-handler-alist=
#+BEGIN_SRC emacs-lisp
)
#+END_SRC
