#+STARTUP: hideall hideblocks

#+TITLE: My Emacs Configurations

* Performance optimization
** Lexical Scoping

Resulting tangled file will use lexical scoping

#+BEGIN_SRC emacs-lisp
  ;;; -*- lexical-binding: t -*-
  (setq-default lexical-binding t)
#+END_SRC

** Startup Benchmarking

This hook reports how long the Emacs startup took, and how many garbage collections there were. The hook is declared at the beginning, and is by definition run at the very end. In this way, the message doesn't get clobbered by other messages during startup.

#+BEGIN_SRC emacs-lisp
  (add-hook 'emacs-startup-hook
            (lambda ()
              (message "Emacs startup took %s with %d garbage collections."
                       (format "%.2f seconds"
                               (float-time
                                (time-subtract after-init-time before-init-time)))
                       gcs-done)))
#+END_SRC

** Prevent Special-Filename Parsing

The rest of the code in this document gets wrapped in a block that sets =file-name-handler-alist= to =nil=. This prevents any special-filename parsing of files loaded from the init file. The block gets closed at the end.

#+BEGIN_SRC emacs-lisp
  (let ((file-name-handler-alist nil))
#+END_SRC

** Config Debug Option

Enable this to debug configuration errors.

#+BEGIN_SRC emacs-lisp
  (setq debug-on-error t)
#+END_SRC

** Garbage Collection Threshold

During startup, the garbage collection threshold is set to the maximum value to prevent garbage collection during load time. This value is reset towards the end for normal usage.

#+BEGIN_SRC emacs-lisp
  (setq gc-cons-threshold most-positive-fixnum)
#+END_SRC

** GUI Disables

Disable all GUI elements. Done early so that Emacs doesn't redisplay in a way that is visually unpleasant on startup.

#+BEGIN_SRC emacs-lisp
  (when (fboundp 'menu-bar-mode) (menu-bar-mode -1))
  (when (fboundp 'tool-bar-mode) (tool-bar-mode -1))
  (when (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))
#+END_SRC

* Automatically Added Variables in =custom.el=

Emacs has its own customization mechanism for many parameters. To prevent clutter in =init.el=, these settings are loaded from =custom.el=.

#+BEGIN_SRC emacs-lisp
  (setq custom-file "~/.emacs.d/custom.el")
  (load custom-file)
#+END_SRC

* Package Management
** Package Repository Declaration

Use the repositories in the following list to download Emacs packages.

#+BEGIN_SRC emacs-lisp
  (customize-set-variable 'package-archives
                          '(("marmalade" . "https://marmalade-repo.org/packages/")
                            ("melpa" . "https://melpa.org/packages/")))
#+END_SRC

** Bootstrap =use-package=

First, initialize the package system. Then, refresh the list of available packages, and install =use-package= if not already. Finally, load =use-package=.

#+BEGIN_SRC emacs-lisp
  (package-initialize)

  (when (not package-archive-contents)
    (package-refresh-contents))

  (when (not (package-installed-p 'use-package))
    (package-install 'use-package))

  (require 'use-package)
#+END_SRC

- =use-package-always-ensure=

  This variable ensures that missing packages are always installed. For libraries where this behaviour is incorrect, the =:ensure nil= declaration will be used.

  #+BEGIN_SRC emacs-lisp
    (customize-set-variable 'use-package-always-ensure t)
  #+END_SRC

- =use-package-always-defer=

  This configuration sets =:defer true= as the default package declaration. This makes Emacs startup much faster by preventing packages from being loaded when Emacs starts, and only doing so when they are needed. For packages that don't work well with this, the =:defer nil= declaration will be used, which forces the package to be loaded at startup. =:defer n= is used to load the package, but only after =n= seconds after startup.

  #+BEGIN_SRC emacs-lisp
    (customize-set-variable 'use-package-always-defer t)
  #+END_SRC

- =use-package-verbose=

  This configuration enables verbose loading of packages which can be useful for debugging. This variable can also be turned off or on according to need.

  #+BEGIN_SRC emacs-lisp
    (customize-set-variable 'use-package-verbose t)
  #+END_SRC

** Automatic Package Updates

=use-package= together with =:ensure= will only install a package if it is not already installed, but does not keep it up-to-date. In order to keep packages up-to-date, =auto-package-update= is used.

#+BEGIN_SRC emacs-lisp
  (use-package auto-package-update
    :config
    (setq auto-package-update-delete-old-versions t)
    (setq auto-package-update-hide-results t)
    (auto-package-update-maybe))
#+END_SRC

** Download Emacs Packages from Github

=quelpa= is installed to directly download and install Emacs packages from their Github repositories (and other places). =quelpa-use-package= is also installed to allow integration with =use-package=.

#+BEGIN_SRC emacs-lisp
  (use-package quelpa
    :defer nil)

  (use-package quelpa-use-package
    :defer nil
    :after quelpa)
#+END_SRC

** Compiled startup files

Tell Emacs to prefer =.el= files if they are newer, even if there are corresponding =.elc= files. Also, use =auto-compile= to autocompile files.

#+BEGIN_SRC emacs-lisp
  (customize-set-variable 'load-prefer-newer t)

  (use-package auto-compile
    :defer nil
    :config (auto-compile-on-load-mode))
#+END_SRC

** Load other lisp files

For =org-mode= and other scripts, use =~/.emacs.d/lisp/= to store. This path is added to startup load path.

#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path "~/.emacs.d/lisp")
#+END_SRC

* Settings

- Load the =cl-lib= library to enable some additional macros (e.g. =lexical-let=).

  #+BEGIN_SRC emacs-lisp
    (use-package cl-lib)
  #+END_SRC

- Update the first 8 lines with the current timestamp when =time-stamp= is run before every save.

  #+BEGIN_SRC emacs-lisp
    (add-hook 'before-save-hook 'time-stamp)
  #+END_SRC

- When beginning of the line, make ~C-k~ remove the whole line instead of just empyting it.

  #+BEGIN_SRC emacs-lisp
    (customize-set-variable 'kill-whole-line t)
  #+END_SRC

- Paste text where the cursor is, not where the mouse is.

  #+BEGIN_SRC emacs-lisp
    (customize-set-variable 'mouse-yank-at-point t)
  #+END_SRC

- Make completion case-insensitive

  #+BEGIN_SRC emacs-lisp
    (setq completion-ignore-case t)
    (customize-set-variable 'read-file-name-completion-ignore-case t)
    (customize-set-variable 'read-buffer-completion-ignore-case t)
  #+END_SRC

- Show line numbers using =display-line-numbers-mode= (only for Emacs version 26 >=).

  #+BEGIN_SRC emacs-lisp
    (when (>= emacs-major-version 26)
      (use-package display-line-numbers
        :defer nil
        :ensure nil
        :config
        (global-display-line-numbers-mode)))
  #+END_SRC

- Highlight trailing whitespace in red, so it's easily visible. Can be turned off if too annoying.

  #+BEGIN_SRC emacs-lisp
    (customize-set-variable 'show-trailing-whitespace t)
  #+END_SRC

- Highlight matching parenthesis

  #+BEGIN_SRC emacs-lisp
    (show-paren-mode)
  #+END_SRC

- Disable hard tabs

  #+BEGIN_SRC emacs-lisp
    (customize-set-variable 'indent-tabs-mode nil)
  #+END_SRC

- Tell Emacs to put all backup files in =~/.emacs.d/backups=

  #+BEGIN_SRC emacs-lisp
    (customize-set-variable
     'backup-directory-alist
     `(("." . ,(concat user-emacs-directory "backups"))))
  #+END_SRC

- WinnerMode makes it possible to cycle and undo window configuration changes. Switch with ~C-c <left>~ or ~C-c <right>~. The ‘fboundp’ test is for those XEmacs installations that don’t have winner-mode available.

  #+BEGIN_SRC emacs-lisp
    (when (fboundp 'winner-mode) (winner-mode))
  #+END_SRC

- Add "unfill" commands. Inverse of the Emacs "fill" commands. Bind ~A-q~ to =unfill-paragraph= and rebind ~M-q~ to the =unfill-toggle= command, which fills/unfills paragraphs alternatively.

  #+BEGIN_SRC emacs-lisp
    (use-package unfill
      :bind
      ("M-q" . unfill-toggle)
      ("A-q" . unfill-paragraph))
  #+END_SRC

- Save the place of the cursor in each file, and restore it upon opening it again

  #+BEGIN_SRC emacs-lisp
    (use-package saveplace
      :defer nil
      :config
      (save-place-mode))
  #+END_SRC

- Delete trailing whitespace before saving a file

  #+BEGIN_SRC emacs-lisp
    (add-hook 'before-save-hook 'delete-trailing-whitespace)
  #+END_SRC

- Suppress "ad-handle-definition: ... redefined" warnings during Emacs startup

  #+BEGIN_SRC emacs-lisp
    (customize-set-variable 'ad-redefinition-action 'accept)
  #+END_SRC

* System-Specific Configuration

Some settings might be OS-specific. Currently, only macOS settings are implemented, although Linux and Windows sections are created. The next block of code decides what OS is running, and sets configurations accordingly.

#+BEGIN_SRC emacs-lisp :noweb no-export
  (cond ((eq system-type 'darwin)
         <<Mac settings>>
         )
        ((eq system-type 'windows-nt)
         <<Windows settings>>
         )
        ((eq system-type 'gnu/linux)
         <<Linux settings>>
         ))
#+END_SRC

** macOS
:PROPERTIES:
:header-args:emacs-lisp: :tangle no :noweb-ref Mac settings
:END:

- Set Command (⌘) to Meta, Option as Alt, right-Option as Super

  #+BEGIN_SRC emacs-lisp :tangle no :noweb-ref Mac settings
    (customize-set-variable 'mac-command-modifier 'meta)
    (customize-set-variable 'mac-option-modifier 'alt)
    (customize-set-variable 'mac-right-option-modifier 'super)
  #+END_SRC

- Use ~⌘-+~ and ~⌘--~ to increase and decrease the font size. ~⌘-=~ is also set to increase as it is convenient on English keyboards.

  #+BEGIN_SRC emacs-lisp :tangle no :noweb-ref Mac settings
    (bind-key "M-+" 'text-scale-increase)
    (bind-key "M-=" 'text-scale-increase)
    (bind-key "M--" 'text-scale-decrease)
  #+END_SRC

- Define a "reset to default text size" function. Bind it to ~⌘-0~.

  #+BEGIN_SRC emacs-lisp :tangle no :noweb-ref Mac settings
    (defun so/text-scale-reset ()
      (interactive)
      (text-scale-set 0))

    (bind-key "M-0" 'so/text-scale-reset)
  #+END_SRC

- Load path settings from shell

  #+BEGIN_SRC emacs-lisp :tangle no :noweb-ref Mac settings
    (use-package exec-path-from-shell
      :defer nil
      :config
      (exec-path-from-shell-initialize))
  #+END_SRC

** Linux

Not immplemented

** Windows

Not implemented

* Keybindings
** Emacs Command Information

The =which-key= package makes Emacs functionality much easier to discover and explore. Through its interactive pop-ip window, information about potential commands is showed as you type.

#+BEGIN_SRC emacs-lisp
  (use-package which-key
    :defer nil
    :diminish which-key-mode
    :config
    (which-key-mode))
#+END_SRC

** =bind-key= package

The =bind-key= package keeps a list of user-configured keybinding. Show by ~M-x~ =describe-personal-keybindings=.

#+BEGIN_SRC emacs-lisp
  (use-package bind-key)
#+END_SRC

- =crux= set ~C-a~ to move to the first non-whitespace character on a line, and then to toggle between that and the beginning of the line.

  #+BEGIN_SRC emacs-lisp
    (use-package crux
      :ensure t
      :bind (("C-a" . crux-move-beginning-of-line)))
  #+END_SRC

- =goto-line=

  Asks for a line number and jump to it

  #+BEGIN_SRC emacs-lisp
    (bind-key "M-g" 'goto-line)
  #+END_SRC

- =other-frame=

  Emulate macOS "next app window" shortcut

  #+BEGIN_SRC emacs-lisp
    (bind-key "M-`" 'other-frame)
  #+END_SRC

- =make-frame-command=

  Emulate macOS "create new window" shortcut

  #+BEGIN_SRC emacs-lisp
    (bind-key "M-n" 'make-frame-command)
  #+END_SRC

- =delete-frame=

  Emulate macOS "close window" shortcut

  #+BEGIN_SRC emacs-lisp
    (bind-key "A-w" 'delete-frame)
  #+END_SRC

* Appearance, buffer/file management and theming

Configurations for the visual, UX, and desktop-management settings.

** Pixel-level scrolling

  #+BEGIN_SRC emacs-lisp
    (when (>= emacs-major-version 26)
      (pixel-scroll-mode))
  #+END_SRC

** Wrap lines

  #+BEGIN_SRC emacs-lisp
    (global-visual-line-mode 1)
  #+END_SRC

** Turn off the error bell

  #+BEGIN_SRC emacs-lisp
    (setq ring-bell-function 'ignore)
  #+END_SRC

** =y-or-n= prompt as default

  #+BEGIN_SRC emacs-lisp
    (defalias 'yes-or-no-p 'y-or-n-p)
  #+END_SRC

** Remove clutter from the modeline. Loaded here, enabled at =use-package= declarations for specific packages.

  #+BEGIN_SRC emacs-lisp
    (use-package diminish
      :defer nil)
  #+END_SRC

** Themes

  #+BEGIN_SRC emacs-lisp
    ;;(use-package solarized-theme)
    ;;(use-package darktooth-theme)
    ;;(use-package kaolin-themes)
    (use-package gruvbox-theme)
    (load-theme 'gruvbox)
  #+END_SRC

** Modeline Customization

  #+BEGIN_SRC emacs-lisp
    (use-package smart-mode-line
      :defer 2
      :config
      (sml/setup)
      :custom
      (sml/theme 'dark)
      (sml/replacer-regexp-list
       '(("^~/\\.emacs\\.d/elpa/"                            ":ELPA:")
         ("^~/\\.emacs\\.d/"                                 ":ED:")
         ("^/sudo:.*:"                                       ":SU:")
         ("^~/Documents/"                                    ":Doc:")
         ("^:\\([^:]*\\):Documento?s/"                       ":\\1/Doc:"))))
  #+END_SRC

** Save Buffer Configuration

  Also bind =desktop-clear=, which kills all open buffers, to ~C-M-s-k~.

  #+BEGIN_SRC emacs-lisp
    (use-package desktop
      :defer nil
      :custom
      (desktop-restore-eager   1 "Restore the first buffer right away")
      (desktop-lazy-idle-delay 1 "Restore the other buffers 1 second later")
      (desktop-lazy-verbose  nil "Be silent about lazily opening buffers")
      :bind
      ("C-M-s-k" . desktop-clear)
      :config
      (desktop-save-mode))
  #+END_SRC

** Make Different Files with Same File Name Unique in Work Space

  #+BEGIN_SRC emacs-lisp
    (use-package uniquify
      :defer 1
      :ensure nil
      :custom
      (uniquify-after-kill-buffer-p t)
      (uniquify-buffer-name-style 'post-forward)
      (uniquify-strip-common-suffix t))
  #+END_SRC

** Highlight Current Line

  #+BEGIN_SRC emacs-lisp
    (use-package hl-line
      :defer nil
      :config
      (global-hl-line-mode))
  #+END_SRC

** Keep a list of recently open buffers.

  #+BEGIN_SRC emacs-lisp
    (use-package recentf
    :defer 1
    :custom
    (recentf-max-menu-items 100)
    (recentf-max-saved-items 100)
    :init
    (recentf-mode))
  #+END_SRC

** =smart M-x= suggests ~M-x~ commands based on recency and frequency. Used by =counsel= as well.

  #+BEGIN_SRC emacs-lisp
    (use-package smex
      :config (smex-initialize))
  #+END_SRC

** Better Buffer Manipulation

  #+BEGIN_SRC emacs-lisp
    (use-package ibuffer
      :disabled
      :bind
      ("C-x C-b" . ibuffer-other-window))
  #+END_SRC

** Command Completion

- =ivy= is a generic completion framework which uses the minibuffer. Turning on =ivy-mode= enables replacement of lots of built in =ido= functionality. By default =ivy= starts filters with =^= which is disabled in this configuration block.

  #+BEGIN_SRC emacs-lisp
    (use-package ivy
      :diminish ivy-mode
      :config
      (setq ivy-initial-inputs-alist nil)
      (ivy-mode t))
  #+END_SRC

- =counsel= is a collection of =ivy= enhanced versions of common Emacs commands. I havn't bound much as =ivy-mode= takes care of most things.

  #+BEGIN_SRC emacs-lisp
    (use-package counsel
      :bind ("M-x" . counsel-M-x))
  #+END_SRC

* Text Editing

** =undo-tree= visualises undo history as a tree for easy navigation.

  #+BEGIN_SRC emacs-lisp
    (use-package undo-tree
      :ensure t
      :diminish undo-tree-mode
      :config
      (global-undo-tree-mode 1))
  #+END_SRC

* Epilogue

** Close =(let ((file-name-handler-alist nil))=

#+BEGIN_SRC emacs-lisp
  )
#+END_SRC

** Reset the value of =gc-cons-threshold=, not to its original value, but larger than default.

#+BEGIN_SRC emacs-lisp
  (setq gc-cons-threshold (* 2 1000 1000))
#+END_SRC
