#+TITLE: My Literate Emacs Configurations
#+AUTHOR: Simen Omholt-Jensen
#+STARTUP:     hideall hidestars
#+PROPERTY:     header-args:emacs-lisp     :tangle "~/.emacs.d/init.el"

* Table of Contents :TOC_3:
- [[#performance-optimization][Performance Optimization]]
  - [[#startup-benchmarking][Startup Benchmarking]]
  - [[#show-debugging-information][Show Debugging Information]]
  - [[#increase-garbage-collection-threshold][Increase Garbage Collection Threshold]]
- [[#package-management][Package Management]]
  - [[#packageel][=package.el=]]
  - [[#package-repositories][Package Repositories]]
  - [[#prepare-packages-for-configuration][Prepare Packages for Configuration]]
  - [[#bootstrap-use-package][Bootstrap =use-package=]]
  - [[#automatically-update-packages-with-auto-package-update][Automatically Update Packages with =auto-package-update=.]]
  - [[#prefer-newer-el-files-over-older-elc-files][Prefer Newer =.el= Files Over Older =.elc= Files.]]
  - [[#automatically-compile-packages-during-startup][Automatically Compile Packages During Startup.]]
  - [[#bind-key][=bind-key=]]
  - [[#diminish][=diminish=]]
  - [[#try][=try=]]
- [[#more-convenient-default-settings][More Convenient Default Settings]]
- [[#disable-guis][Disable GUIs]]
- [[#functionality][Functionality]]
  - [[#window-navigation][Window Navigation]]
  - [[#ivy--counsel--swiper][=Ivy= / =Counsel= / =Swiper=]]
    - [[#smart-mx][=smart-mx=]]
    - [[#ivy-is-an-interactive-interface-for-completion-in-emacs][=Ivy= is an interactive interface for completion in Emacs.]]
  - [[#undo-tools][Undo tools]]
  - [[#expand-region][Expand region]]
  - [[#toggle-line-comment][Toggle Line Comment]]
  - [[#auto-completion][Auto Completion]]
  - [[#iedit][=iedit=]]
  - [[#yasnippets][=yasnippets=]]
  - [[#hungry-delete][=hungry-delete=]]
  - [[#aggressive-indent][=aggressive-indent=]]
  - [[#restart-emacs][=restart-emacs=]]
  - [[#google-this][=google-this=]]
  - [[#flycheck][=flycheck=]]
  - [[#killing-emacs][Killing emacs]]
- [[#os-specific-settings][OS Specific Settings]]
  - [[#macos][macOS]]
  - [[#windows][Windows]]
  - [[#linux][Linux]]
- [[#org-mode][org-mode]]
  - [[#toc-org][=toc-org=]]
  - [[#org-bullets][=org-bullets=]]
  - [[#revealjs][=reveal.js=]]
- [[#appearance][Appearance]]
  - [[#themes][Themes]]
  - [[#beacon][Beacon]]
- [[#coding][Coding]]
  - [[#general][General]]
    - [[#insert-shebang][=insert-shebang=]]
  - [[#python][Python]]
    - [[#condael][=conda.el=]]
    - [[#company-jedi][=company-jedi=]]
- [[#elisp-functions][Elisp functions]]
  - [[#rename-open-file-and-change-buffer-name-as-well][Rename open file and change buffer name as well]]
  - [[#move-to-matching-parenthesis][Move to matching parenthesis]]
- [[#desktop][Desktop]]
  - [[#minimal-setup][Minimal Setup]]
- [[#keybindings][Keybindings]]
  - [[#which-key][which-key]]
  - [[#list-of-bindings][List of Bindings]]
- [[#experimental][Experimental]]
- [[#epilogue][Epilogue]]
  - [[#sensible-garbage-collection-threshold][Sensible Garbage Collection Threshold]]

* Performance Optimization
** Startup Benchmarking

First, declare a hook which will benchmark the startup process. It reports how long the it took to start up, and how many garbage collections were performed.

[[https://blog.d46.us/advanced-emacs-startup/][More Information]]

#+BEGIN_SRC emacs-lisp
  (add-hook 'emacs-startup-hook
            (lambda ()
              (message "Emacs ready in %s with %d garbage collections."
                       (format "%.2f seconds"
                               (float-time
                                (time-subtract after-init-time before-init-time)))
                       gcs-done)))
#+END_SRC

** Show Debugging Information

Toggle this to receive more information when encountering startup errors.

#+BEGIN_SRC emacs-lisp
  (setq debug-on-error t)
#+END_SRC

** Increase Garbage Collection Threshold

When Emacs loads files, packages or libraries, the data is placed in normal storage. When the normal storage runs out, Emacs asks the operating system to allocate more memory. This process is known as garbage collection, and as the default value for Emacs is only ~800kB, it happens quite frequently during startup. As such, we can improve startup performance by increasing this value. In the Epilogue, this value is lowered back down to a sensible default.
[[https://github.com/zzamboni/dot-emacs/blob/master/init.org#performance-optimization][More Information]]

#+BEGIN_SRC emacs-lisp
  (setq gc-cons-threshold most-positive-fixnum)
#+End_SRC

* Package Management
** =package.el=

By default, Emacs 24 or later comes with a built-in package management system (=package.el=). To add further functionality such as adding package repositories and tweaking package configurations, =package.el= needs to be loaded in the =init.el= file during startup.
[[https://www.gnu.org/software/emacs/manual/html_mono/emacs.html#Package-Installation][More Information]]

#+BEGIN_SRC emacs-lisp
  (require 'package)
#+END_SRC

** Package Repositories

By default, Emacs comes with the Emacs Lisp Package Archive (ELPA). As the packages need to be FSF-sanctioned, there aren't that many to choose from. By adding the Milkypostman's Emacs Lisp Package Archive ([[https://melpa.org/][MELPA]]), an enormous amount of packages become available. Remember to add ~https~ to urls.

#+BEGIN_SRC emacs-lisp
  (setq-default package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                                   ("melpa" . "https://melpa.org/packages/")
                                   ("org" . "https://orgmode.org/elpa/")
                                   ;; ("marmalade" . "https://marmalade-repo.org/packages/")
                                   ))
#+END_SRC

** Prepare Packages for Configuration

- Run =package-initialize= to set up the load-paths and autoloads for installed packages. [[https://www.emacswiki.org/emacs/InstallingPackages][More Information]]

#+BEGIN_SRC emacs-lisp
  (package-initialize)
#+END_SRC

- Set =package-enable-at-startup= to =nil= to prevent superfluous loading of packages. [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Package-Installation.html][More Information]]

#+BEGIN_SRC emacs-lisp
  (setq-default package-enable-at-startup nil)
#+END_SRC

** Bootstrap =use-package=

- The =use-package= macro allows cleaner configuration of package loading and installation. [[https://github.com/jwiegley/use-package][More Information]]

#+BEGIN_SRC emacs-lisp
  (when (not (package-installed-p 'use-package))
    (package-refresh-contents)
    (package-install 'use-package))
  (eval-when-compile
    (require 'use-package))
#+END_SRC

- By setting =use-package-always-ensure= to =t=, =use-package= will install packages that are not already installed.
[[https://github.com/jwiegley/use-package#package-installation][More Information]]

#+BEGIN_SRC emacs-lisp
  (require 'use-package-ensure)
  (setq use-package-always-ensure t)
#+END_SRC

** Automatically Update Packages with =auto-package-update=.

[[https://github.com/rranelli/auto-package-update.el][More Information]]

#+BEGIN_SRC emacs-lisp
  (use-package auto-package-update
    :config
    (setq-default auto-package-update-delete-old-versions t)
    (setq-default auto-package-update-hide-results t)
    (auto-package-update-maybe))
#+END_SRC

** Prefer Newer =.el= Files Over Older =.elc= Files.

#+BEGIN_SRC emacs-lisp
  (setq-default load-prefer-newer t)
#+END_SRC

** Automatically Compile Packages During Startup.
[[https://github.com/emacscollective/auto-compile][
More Information]]

#+BEGIN_SRC emacs-lisp
  (use-package auto-compile
    :config
    (auto-compile-on-load-mode)
  (auto-compile-on-save-mode))
#+END_SRC

** =bind-key=

#+BEGIN_SRC emacs-lisp
  (require 'bind-key)
#+END_SRC

** =diminish=

The =diminish= package makes it possible to remove clutter from the modeline. The =:diminish= keyword in the =use-package= declarations signify =diminish= invocation.
[[https://github.com/myrjola/diminish.el][More Information]]

#+BEGIN_SRC emacs-lisp
  (use-package diminish)
#+END_SRC

** =try=

The =try= package let's you try new packages without installed them. On the next restart of Emacs, they are not loaded.

#+BEGIN_SRC emacs-lisp
  (use-package try)
#+END_SRC

* More Convenient Default Settings

- Set frame title to =[user@hostname]=

#+BEGIN_SRC emacs-lisp
  (setq-default frame-title-format (list "[" user-login-name "@" (system-name) "] %b"))
#+END_SRC

- Display line numbers

#+BEGIN_SRC emacs-lisp
  (when (version<= "26.0.50" emacs-version )
    (global-display-line-numbers-mode))
#+END_SRC

- Display columns numbers

#+BEGIN_SRC emacs-lisp
  (setq column-number-mode t)
#+END_SRC

- Don't show the startup message. =inhibit-startup-message= and =inhibit-splash-screen= are aliases for this variable.

#+BEGIN_SRC emacs-lisp
  (setq-default inhibit-startup-screen t)
#+END_SRC

- Set initial scratch message to =nil=.

#+BEGIN_SRC emacs-lisp
  (setq-default initial-scratch-message nil)
#+END_SRC

- Place the automatically added 'customize-variables' in =custom.el=.

#+BEGIN_SRC emacs-lisp
  (setq-default custom-file "~/.emacs.d/custom.el")
  (load custom-file)
#+END_SRC

- Disable lock files

#+BEGIN_SRC emacs-lisp
  (setq-default create-lockfiles nil)
#+END_SRC

- Save automatically generated backup files to =~/.emacs.d/backups/=.

#+BEGIN_SRC emacs-lisp
  (setq-default backup-directory-alist '(("." . "/Users/simenojensen/.emacs.d/backups")))
#+END_SRC

- Set the column width to 80 characters.

#+BEGIN_SRC emacs-lisp
  (setq-default fill-column 80)
#+END_SRC

- Prefer lines to wrap.

#+BEGIN_SRC emacs-lisp
  (global-visual-line-mode t)
#+END_SRC

- Don't use hard tabs.

#+BEGIN_SRC emacs-lisp
  (setq-default indent-tabs-mode nil)
#+END_SRC

- Disable the cursor jump when it moves out of the window.

#+BEGIN_SRC emacs-lisp
  (setq-default scroll-conservatively 101)
#+END_SRC

- Change =yes-or-no= prompt to =y-or-n=.

#+BEGIN_SRC emacs-lisp
  (fset 'yes-or-no-p 'y-or-n-p)
#+END_SRC

- Delete trailing whitespace when a file is saved.

#+BEGIN_SRC emacs-lisp
  (add-hook 'before-save-hook 'delete-trailing-whitespace)
#+END_SRC

- Automatically update buffers if a file content on the disk has changed.

#+BEGIN_SRC emacs-lisp
  (global-auto-revert-mode t)
#+END_SRC

- Save position of the point in file.

#+BEGIN_SRC emacs-lisp
  (save-place-mode t)
#+END_SRC

- Highlight the line with the point.

#+BEGIN_SRC emacs-lisp
  (global-hl-line-mode t)
#+END_SRC


- When saving a file, update the time stamp of the first 8 lines to the current time.

#+BEGIN_SRC emacs-lisp
  (add-hook 'before-save-hook 'time-stamp)
#+END_SRC

- Warn when opening a file larger than 100MB

#+BEGIN_SRC emacs-lisp
  (setq large-file-warning-threshold 100000000)
#+END_SRC

* Disable GUIs

- Don't show the menu bar.

#+BEGIN_SRC emacs-lisp
  (menu-bar-mode -1)
#+END_SRC

- Don't show the tool bar.

#+BEGIN_SRC emacs-lisp
  (when (fboundp 'tool-bar-mode)
    (tool-bar-mode -1))
#+END_SRC

- Don't show the scroll bar.

#+BEGIN_SRC emacs-lisp
  (when (fboundp 'scroll-bar-mode)
    (scroll-bar-mode -1))
#+END_SRC

- Disable the blinking cursor.

#+BEGIN_SRC emacs-lisp
  (blink-cursor-mode -1)
#+END_SRC

- Disable the =ring-bell= function.

#+BEGIN_SRC emacs-lisp
  (setq-default ring-bell-function 'ignore)
#+END_SRC

* Functionality
** Window Navigation

=ace-window= offers fast window navigation with [[https://github.com/zamansky/using-emacs/blob/master/myinit.org#ace-windows-for-easy-window-switching][customizable]] prompts.
[[https://github.com/abo-abo/ace-window][More Information]]

#+BEGIN_SRC emacs-lisp
  (use-package ace-window
    :init
    (custom-set-faces
     '(aw-leading-char-face
       ((t (:inherit ace-jump-face-foreground :height 3.0)))))
    :bind
    ("C-x o" . ace-window))
#+END_SRC

Built-in =winner-mode= for remembering previous window actions.

#+BEGIN_SRC emacs-lisp
  (winner-mode 1)
#+END_SRC

** =Ivy= / =Counsel= / =Swiper=
*** =smart-mx=

=smart M-x= suggests ~M-x~ commands based on recency and frequency. Used by Counsel indirectely.

#+BEGIN_SRC emacs-lisp
  (use-package smex)
#+END_SRC

*** =Ivy= is an interactive interface for completion in Emacs.
[[https://oremacs.com/swiper/][More Information]]

#+BEGIN_SRC emacs-lisp
  (use-package counsel
    :bind
    ("C-x C-f" . counsel-find-file)
    ("C-h f" . counsel-describe-function)
    ("C-h v" . counsel-describe-variable)
    ("C-h l" . counsel-find-library)
    ("C-h i" . counsel-info-lookup-symbol)
    ("C-h u" . counsel-unicode-char)
    ("M-x" . counsel-M-x)
    ("M-v" . counsel-yank-pop)
    )

  (use-package ivy
    :diminish
    :bind
    ("C-x b" . ivy-switch-buffer)
    :config
    (ivy-mode 1)
    (setq ivy-initial-inputs-alist nil)
    (setq ivy-display-style 'fancy)
    (setq ivy-use-virtual-buffers t)
    (setq ivy-count-format "(%d/%d) ")
    )

  (use-package swiper
    :bind
    ("C-s" . swiper-isearch)
    )
#+END_SRC

** Undo tools

=undo-tree= visualises undo history as a tree for easy navigation.

#+BEGIN_SRC emacs-lisp
  (use-package undo-tree
    :diminish
    :bind
    ("C-x u" . undo-tree-visualize)
    :config
    (global-undo-tree-mode)
    )
#+END_SRC

** Expand region

=expand-region= expands your marked region around the cursor semantically depending on mode.

#+BEGIN_SRC emacs-lisp
  (use-package expand-region
    :bind ("C-=" . er/expand-region))
#+END_SRC

** Toggle Line Comment

Comment or uncomment the current line. Bind to ~C-;~.

#+BEGIN_SRC emacs-lisp
  (defun my/toggle-comment-on-line ()
    (interactive)
    (comment-or-uncomment-region (line-beginning-position) (line-end-position)))

  (bind-key "C-;" 'my/toggle-comment-on-line)
#+END_SRC

** Auto Completion

I will be using =company= for autocompletion.
[[http://company-mode.github.io/][More Information]]

#+BEGIN_SRC emacs-lisp
  (use-package company
    :diminish
    :config
    (setq-default company-idle-delay 0)
    (setq company-minimum-prefix-length 3)
    (global-company-mode t)
    :bind (:map company-active-map
           ("C-n" . company-select-next)
           ("C-p" . company-select-previous))
    )
#+END_SRC

[[https://github.com/company-mode/company-quickhelp][More Information]]

#+BEGIN_SRC emacs-lisp
  (use-package pos-tip)

  (use-package company-quickhelp
    :config
    (company-quickhelp-mode)
    )
#+END_SRC

[[https://github.com/company-mode/company-statistics][More Information]]

#+BEGIN_SRC emacs-lisp
(use-package company-statistics
  :config
  (company-statistics-mode))
#+END_SRC

** =iedit=

=iedit= allows you to edit multiple occurrences of a symbol or region.
[[https://www.emacswiki.org/emacs/Iedit][More Information]]

#+BEGIN_SRC emacs-lisp
  (use-package iedit
    :bind
    ("M-;" . iedit-mode))
#+END_SRC

** =yasnippets=

=yasnippets= is a template system.
[[https://github.com/joaotavora/yasnippet][More Information]]

#+BEGIN_SRC emacs-lisp
  (use-package yasnippet
    :diminish
    :config
    (use-package yasnippet-snippets)
    (yas-global-mode 1))
#+END_SRC

** =hungry-delete=

Delete trailing whitespace

#+BEGIN_SRC emacs-lisp
  (use-package hungry-delete
    :config
    (global-hungry-delete-mode))
#+END_SRC

** =aggressive-indent=

[[https://github.com/joaotavora/aggressive-indent-mode][More Information]]

#+BEGIN_SRC emacs-lisp
  ;; (use-package aggressive-indent
    ;; :hook
    ;; (python-mode . aggressive-indent-mode)
    ;; )
#+END_SRC

** =restart-emacs=

Restart Emacs from within Emacs.
[[https://github.com/iqbalansari/restart-emacs][More Information]]

#+BEGIN_SRC emacs-lisp
  (use-package restart-emacs)
#+END_SRC

** =google-this=

[[http://pragmaticemacs.com/emacs/google-search-from-inside-emacs/][More Information]]

#+BEGIN_SRC emacs-lisp
  (use-package google-this
    :config
    (google-this-mode t)
    )
#+END_SRC

** =flycheck=

#+BEGIN_SRC emacs-lisp
  (use-package flycheck
    :init
    (global-flycheck-mode))
#+END_SRC

** Killing emacs

Do not confirm when killing emacs.

#+BEGIN_SRC emacs-lisp
  (setq-default confirm-kill-emacs nil)
#+END_SRC

Do not confirm when killing processes.

#+BEGIN_SRC emacs-lisp
  (setq-default confirm-kill-processes nil)
#+END_SRC

* OS Specific Settings

Detect which OS Emacs is being run on, and configure keybindings accordingly.

#+BEGIN_SRC emacs-lisp
  (cond
#+END_SRC

** macOS

#+BEGIN_SRC emacs-lisp
  ((eq system-type 'darwin)
#+END_SRC

By setting the ~M~ to ~⌘~, ~A~ to ~^~ (left option)  and ~S~ to ~^~ (right option), we can emulate some of the macOS keyboard configurations.

#+BEGIN_SRC emacs-lisp
  (customize-set-variable 'mac-command-modifier 'meta)
  (customize-set-variable 'mac-option-modifier 'alt)
  (customize-set-variable 'mac-right-option-modifier 'super)
#+END_SRC

Next, we are binding ~M-=~ to increase the font size, and ~M--~ to decrease the font size.

#+BEGIN_SRC emacs-lisp
  (bind-key "M-=" 'text-scale-increase)
  (bind-key "M--" 'text-scale-decrease)
#+END_SRC

Further, a function borrowed from [[https://zzamboni.org/post/my-emacs-configuration-with-commentary/#mac][zzamboni]] is implemented and bound to ~M-0~.

#+BEGIN_SRC emacs-lisp
  (defun my/text-scale-reset ()
    "Reset text scaling to default"
    (interactive)
    (text-scale-set 0))

  (bind-key "M-0" 'my/text-scale-reset)
#+END_SRC

Lastly, we make sure the =$PATH= is loaded from the default shell.
[[https://github.com/purcell/exec-path-from-shell][More Information]]

#+BEGIN_SRC emacs-lisp
    (use-package exec-path-from-shell
      :defer nil
      :config
      (exec-path-from-shell-initialize)
      (exec-path-from-shell-copy-env "AIRTABLE_API_KEY")
      (exec-path-from-shell-copy-env "TSI_ENVIROMENT")
      (exec-path-from-shell-copy-env "TSI_TENANT_ID")
      (exec-path-from-shell-copy-env "TSI_CLIENT_ID")
      (exec-path-from-shell-copy-env "TSI_CLIENT_SECRET")
      (exec-path-from-shell-copy-env "TSI_APPLICATION_NAME")
      (exec-path-from-shell-copy-env "VIRTUAL_ENV")
      (exec-path-from-shell-copy-env "LANG") ;; unsure
      (exec-path-from-shell-copy-env "LC_ALL") ;; unsure
      (exec-path-from-shell-copy-env "LC_CTYPE") ;; unsure
      )
  )
#+END_SRC

** Windows

Not implemented.

#+BEGIN_SRC emacs-lisp
  ((eq system-type 'windows-nt))
#+END_SRC

** Linux

Not Implemented

#+BEGIN_SRC emacs-lisp
  ((eq system-type 'gnu/linux))
 )
#+END_SRC

* org-mode

Install org-mode from the org package repository.

#+BEGIN_SRC emacs-lisp
  (use-package org
    :pin org
    :config
    ;; add "<s <TAB>" for code block completion
    (add-to-list 'org-modules 'org-tempo)
    )
#+END_SRC

** =toc-org=

Install the =toc-org= package to automatically generate an updated table of contents.

#+BEGIN_SRC emacs-lisp
  (use-package toc-org
    :after org
    :hook
    (org-mode . toc-org-enable))
#+END_SRC

** =org-bullets=

#+BEGIN_SRC emacs-lisp
  (use-package org-bullets
    :hook (org-mode . (lambda () (org-bullets-mode t))
                    ))
 #+END_SRC

** =reveal.js=

Install reveal.js from [[https://github.com/hakimel/reveal.js/][here]]. Then, install [[https://github.com/hexmode/ox-reveal][=ox-reveal=]] and [[https://github.com/hniksic/emacs-htmlize][=htmlize=]].

#+BEGIN_SRC emacs-lisp
  (use-package ox-reveal
    :ensure ox-reveal
    :config
    (setq org-reveal-root "/Users/simenojensen/.emacs.d/reveal.js/")
    (setq org-reveal-mathjax t)
    )

  (use-package htmlize)
#+END_SRC

* Appearance
** Themes

#+BEGIN_SRC emacs-lisp
  ;;(use-package solarized-theme)
  ;;(use-package darktooth-theme)
  ;;(use-package kaolin-themes)
  (use-package gruvbox-theme
    :config
    (load-theme 'gruvbox)
    )
#+END_SRC

- Highlight matching parenthesis

#+BEGIN_SRC emacs-lisp
  (use-package paren
    :config
    (show-paren-mode t)
    (set-face-background 'show-paren-match "#EC7063")
    (set-face-foreground 'show-paren-match "Red1")
    (set-face-attribute 'show-paren-match nil :weight 'extra-bold)
    )
#+END_SRC

** Beacon

[[https://github.com/Malabarba/beacon][More Information]]

#+BEGIN_SRC emacs-lisp
  (use-package beacon
    :config
    (beacon-mode 1)
    (setq beacon-color "#39FF14")
    )
#+END_SRC

* Coding
** General

*** =insert-shebang=

[[https://carlfg.wordpress.com/2013/10/21/insert-shebang-extension-for-emacs/][More Information]]

#+BEGIN_SRC emacs-lisp
  (use-package insert-shebang)
#+END_SRC

** Python

[[https://www.emacswiki.org/emacs/PythonProgrammingInEmacs#toc30][More Information]]

#+BEGIN_SRC emacs-lisp
  (setq python-shell-interpreter "jupyter"
        python-shell-interpreter-args "console --simple-prompt"
        python-shell-prompt-detect-failure-warning nil)

  ;; (setq python-shell-interpreter "ipython"
  ;;       python-shell-interpreter-args "--simple-prompt -i")

  (defun my/add-python-shell-completion-native-disabled-interpreters ()
    (add-to-list 'python-shell-completion-native-disabled-interpreters "jupyter"))

  (add-hook 'python-mode-hook 'my/add-python-shell-completion-native-disabled-interpreters)

  (use-package ein
    :config
    (setq ein:output-area-inlined-images t)
    )
#+END_SRC

*** =conda.el=

This package lets you activate your conda environments. The setup works for miniconda installed by homebrew.
[[https://github.com/necaris/conda.el][More Information]]

Usage:
- ~M-x conda-env-activate~
- ~M-x conda-env-deactivate~

#+BEGIN_SRC emacs-lisp
  (use-package conda
    :init
    (setq conda-anaconda-home "/usr/local/Caskroom/miniconda/base/")
    :config
    ;; interactive shell support
    (conda-env-initialize-interactive-shells)
    ;; eshell support
    (conda-env-initialize-eshell)
    ;; auto-activate
    (conda-env-autoactivate-mode t)
    )
#+END_SRC

*** =company-jedi=

[[https://github.com/emacsorphanage/company-jedi][More Information]]

#+BEGIN_SRC emacs-lisp
  (use-package company-jedi
    :diminish
    :config
    (setq-default jedi:complete-on-dot t)
    (eval-after-load "company-jedi"
      '(setq jedi:server-command (list "/usr/local/Caskroom/miniconda/base/envs/emacs-jedi/bin/python" jedi:server-script)))
    (defun my/python-mode-hook ()
      (add-to-list 'company-backends 'company-jedi))
    :hook
    (python-mode . my/python-mode-hook)
    (python-mode . jedi:setup)
    (conda-postactivate . jedi:stop-server)
    (conda-postdeactivate . jedi:stop-server)
    )
#+END_SRC

* Elisp functions
** Rename open file and change buffer name as well

#+BEGIN_SRC emacs-lisp
  ;; source: http://steve.yegge.googlepages.com/my-dot-emacs-file
  (defun my/rename-file-and-buffer (new-name)
    "Renames both current buffer and file it's visiting to NEW-NAME."
    (interactive "sNew name: ")
    (let ((name (buffer-name))
          (filename (buffer-file-name)))
      (if (not filename)
          (message "Buffer '%s' is not visiting a file!" name)
        (if (get-buffer new-name)
            (message "A buffer named '%s' already exists!" new-name)
          (progn
            (rename-file filename new-name 1)
            (rename-buffer new-name)
            (set-visited-file-name new-name)
            (set-buffer-modified-p nil))))))

#+END_SRC

** Move to matching parenthesis

[[https://www.emacswiki.org/emacs/NavigatingParentheses#toc8][More Information]]

 #+BEGIN_SRC emacs-lisp
    (defun goto-match-paren (arg)
        "Go to the matching parenthesis if on parenthesis. Else go to the
      opening parenthesis one level up."
        (interactive "p")
        (cond ((looking-at "\\s\(") (forward-list 1))
              (t
               (backward-char 1)
               (cond ((looking-at "\\s\)")
                      (forward-char 1) (backward-list 1))
                     (t
                      (while (not (looking-at "\\s("))
                        (backward-char 1)
                        (cond ((looking-at "\\s\)")
                               (message "->> )")
                               (forward-char 1)
                               (backward-list 1)
                               (backward-char 1)))
                        ))))))
 #+END_SRC

* Desktop
** Minimal Setup

[[https://www.emacswiki.org/emacs/Desktop][More Information]]

#+BEGIN_SRC emacs-lisp
  ;; use only one desktop
  (setq desktop-path '("~/.emacs.d/"))
  (setq desktop-dirname "~/.emacs.d/")
  (setq desktop-base-file-name "emacs-desktop")

  ;; remove desktop after it's been read
  ;; (add-hook 'desktop-after-read-hook
            ;; '(lambda ()
               ;; desktop-remove clears desktop-dirname
               ;; (setq desktop-dirname-tmp desktop-dirname)
               ;; (desktop-remove)
               ;; (setq desktop-dirname desktop-dirname-tmp)))

  (defun saved-session ()
    (file-exists-p (concat desktop-dirname "/" desktop-base-file-name)))

  ;; use session-restore to restore the desktop manually
  (defun session-restore ()
    "Restore a saved emacs session."
    (interactive)
    (if (saved-session)
        (desktop-read)
      (message "No desktop found.")))

  ;; use session-save to save the desktop manually
  (defun session-save ()
    "Save an emacs session."
    (interactive)
    (if (saved-session)
        (if (y-or-n-p "Overwrite existing desktop? ")
            (desktop-save-in-desktop-dir)
          (message "Session not saved."))
    (desktop-save-in-desktop-dir)))

  ;; ask user whether to restore desktop at start-up
  (add-hook 'after-init-hook
            '(lambda ()
               (if (saved-session)
                   (if (y-or-n-p "Restore desktop? ")
                       (session-restore)))))
#+END_SRC

* Keybindings
** which-key

The =which-key= package automatically displays potential command information as command keys are typed. This makes it easy to explore Emacs functionality.
[[https://github.com/justbur/emacs-which-key][More Information]]

#+BEGIN_SRC emacs-lisp
  (use-package which-key
    :diminish which-key-mode
    :config
    (setq which-key-idle-delay 0.5)
    (which-key-mode))
#+END_SRC

** List of Bindings

- Go to line number.

#+BEGIN_SRC emacs-lisp
  (bind-key "M-g" 'goto-line)
#+END_SRC

- Create new frame (emulate macOS' "new window" shortcut).

#+BEGIN_SRC emacs-lisp
  ;; (bind-key "M-n" 'make-frame)
#+END_SRC

- Revert Buffer

#+BEGIN_SRC emacs-lisp
  (bind-key "M-r" 'revert-buffer)
#+END_SRC


- Focus next frame (emulate macOS' "focus next window" shortcut).

#+BEGIN_SRC emacs-lisp
  ;; (bind-key "M-`" 'other-frame)
#+END_SRC

- =crux= sets ~C-a~ to move to the first non-whitespace character on a line, and then to toggle between that and the beginning of the line.

#+BEGIN_SRC emacs-lisp
  (use-package crux
    :bind ("C-a" . crux-move-beginning-of-line))
#+END_SRC

- =goto-match-paren=

#+BEGIN_SRC emacs-lisp
  (bind-key "C-M-n" 'goto-match-paren)
#+END_SRC

- =ibuffer=

#+BEGIN_SRC emacs-lisp
  (bind-key "C-x C-b" 'ibuffer)
#+END_SRC

* Experimental

#+BEGIN_SRC emacs-lisp
  (use-package magit
    :bind
    ("C-x g" . magit-status)
    )
#+END_SRC

#+BEGIN_SRC emacs-lisp
    (use-package rainbow-delimiters
      :hook
      (prog-mode . rainbow-delimiters-mode)
      )
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (use-package tex-site
    :ensure auctex
    :mode ("\\.tex\\'" . latex-mode)
    :config
    (setq TeX-auto-save t)
    (setq TeX-parse-self t)
    (setq TeX-save-query nil)
    (setq TeX-PDF-mode t)
    (setq-default TeX-master nil)
    )
#+END_SRC


* Epilogue
** Sensible Garbage Collection Threshold

Here, the =gc-cons-threshold= is set to a sensible value for normal use.

#+BEGIN_SRC emacs-lisp
  (setq gc-cons-threshold (* 2 1000 1000))
#+END_SRC
